import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["500"], subsets: ["devanagari"] });

export const metadata: Metadata = {
  title: "Nicolas Sanjaya | Fullstack Web Developer",
  description: "Generated by create next app",
  icons: {
    icon: { url: "/logo.png" },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <link rel="icon" href="/logo.png" sizes="any" />
      <body className={`${poppins.className} bg-gray-50`}>{children}</body>
    </html>
  );
}
